#! /bin/sh

read -e -p "please run this command in another terminal before continuing
while true; do leaks alagache.filler; sleep 1; clear; done" TOTO
if [ "$#" -eq 0 ];
then
	echo "need the testing file as argument"
else
	if [ -f "$1" ];
	then
		./alagache.filler "$1" > result
	else
		echo "test file does not exist"
	fi
fi
